name: vet_project_flutter_frontend
description: Veterinerlik Fakültesi Patoloji Ana Bilim Dalı Veri Yönetim Yazılımı
authors:
  - Ahmet Çetinkaya <ahmetcetinkaya.me>

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  flutter_quill: ^4.1.3
  flutter_inappwebview: ^5.4.3+1
  delta_markdown: ^0.6.0
  markdown: ^5.0.0
  html2md: ^1.2.6
  dropdown_search: ^3.0.1
  camera: ^0.9.4+21
  path_provider: ^2.0.9
  path: ^1.8.0
  swipe_image_gallery: ^0.5.1
  cached_network_image: ^3.2.0
  persistent_bottom_nav_bar: ^4.0.2
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.2
  localstore: ^1.2.3
  gallery_saver: ^2.3.2
  external_path: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
