// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJmj8t41MSXLvjEoTu1dSV57HfP9FQRdk',
    appId: '1:210792734232:web:3cf68f0af0842ef23f6d6d',
    messagingSenderId: '210792734232',
    projectId: 'not-defteri-fd5a0',
    authDomain: 'not-defteri-fd5a0.firebaseapp.com',
    storageBucket: 'not-defteri-fd5a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-oGItMfEMx48aDBfu5JMT9IinaZpYqOw',
    appId: '1:210792734232:android:2961a7e80d7583463f6d6d',
    messagingSenderId: '210792734232',
    projectId: 'not-defteri-fd5a0',
    storageBucket: 'not-defteri-fd5a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ_7F5p5ev_VIlN9AEMtkzkQYI2c9AobQ',
    appId: '1:210792734232:ios:6961703ce1e088653f6d6d',
    messagingSenderId: '210792734232',
    projectId: 'not-defteri-fd5a0',
    storageBucket: 'not-defteri-fd5a0.appspot.com',
    iosClientId: '210792734232-o2q54u1vg1thre2qd9b93le2i51h7n7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.notDefteri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ_7F5p5ev_VIlN9AEMtkzkQYI2c9AobQ',
    appId: '1:210792734232:ios:6961703ce1e088653f6d6d',
    messagingSenderId: '210792734232',
    projectId: 'not-defteri-fd5a0',
    storageBucket: 'not-defteri-fd5a0.appspot.com',
    iosClientId: '210792734232-o2q54u1vg1thre2qd9b93le2i51h7n7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.notDefteri',
  );
}
