name: cssdemo
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  css_colors: ^1.0.0



  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^1.0.0

flutter:

 
  uses-material-design: true

  
