class Veriler {

  List<String> dogum = [
    'Tek',
    'İkiz ',
    'Üçüz',
    'Dördüz',
    'Beşiz',
    'Altız',
  ];
  List<String> hastalikismi = [
    'MASTİTİS (MEME İLTİHABI)',
    'HİPOKALSEMİ (SÜT HUMMASI)',
    'KETOSİS',
    'TİMPANİ(ŞİŞME)',
    'ANTRAKS (ŞARBON)',
    'YANIKARA',
    'BRUSELLOZİS (YAVRU ATMA HASTALIĞI)',
    'PİROPLAZMOZ (KAN İŞEME, AĞRIMA)',
    'SIĞIR BRUSELLOZU',
    'SIĞIR TÜBERKÜLOZU',
    'SIĞIR VEBASI',
    'SIĞIRLARIN NODÜLER EKZANTEMİ',
    'SIĞIRLARIN SÜNGERİMSİ BEYİN HASTALIĞI (BSE)',
    'ŞAP - A',
    'ŞAP - ASİA1',
    'ŞAP - O',
    'ŞAP - TİPLENDİRİLEMEDİ',
    'ŞAP ?',
    'Şap Grubu(Hepsi)',
  ];
  List<String> asiismi = [
    'ŞAP AŞISI',
    'SIĞIR VEBASI AŞISI ',
    'ŞARBON (ANTHRAKS) AŞISI',
    'BRUCELLA AŞISI',
    'ENTEROTOKSEMİ AŞISI',
    'LEPTOSPİROZ AŞISI',
    'PASTÖRELLA AŞISI',
    'SEPTICEMIA NEONATORUM AŞISI',
    'YANIKARA AŞISI',
    'PARATÜBERKÜLOZ AŞISI',
    'BOTULİSMUS AŞISI',
    'THEİLERİA ANNULATA AŞISI',
    'IBR AŞISI',
    'MASTİTİS AŞISI', 
  ];
  List<String> irk = [
    'Montafon',
    'Brangus',
    'Simmental',
    'Holstein',
    'Holstein Friesian',
    'Jersey',
    'Charolais',
    'Yerli Kara',
    'Doğu Anadolu Kırmızısı',
    'Boz Irk',
    'Güney Anadolu Kırmızısı',
    'Kırım Sığırı',
    'Zavot Sığırı',
  ];
}
