name: waterreminder
description: Water reminder App.
publish_to: 'none'
version: 1.0.4+5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animations: ^2.0.0
  flutter_bloc: ^7.0.0
  rxdart: ^0.26.0
  flutter_native_splash: 

flutter_native_splash:
  color: "#f5f5f5"
  image: assets/Saly-13.png
  android: true
  ios: true


dev_dependencies: 
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/water.png"

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  
  fonts:
    - family: AppSymbols
      fonts:
      - asset: fonts/AppSymbols.ttf

    - family: Comfortaa
      fonts:
      - asset: fonts/Comfortaa-Regular.ttf

      - asset: fonts/Comfortaa-Light.ttf
        weight: 300
      
      - asset: fonts/Comfortaa-Medium.ttf
        weight: 500

      - asset: fonts/Comfortaa-SemiBold.ttf
        weight: 600
      
      - asset: fonts/Comfortaa-Bold.ttf
        weight: 700

